name: CI

on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Check code consistency
        run: bundle exec rubocop
      - name: Setup database
        run: bundle exec rake db:prepare
        env:
          RAILS_ENV: test
          DATABASE_HOST: localhost
      - name: Integration tests
        run: bundle exec rspec
        env:
          DATABASE_HOST: localhost
