name: CI

on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Check code consistency
        run: bundle exec rubocop
      - name: Integration tests
        run: bundle exec rspec
